apiVersion: apps/v1
kind: Deployment
metadata:
  name: rewards-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rewards-server
  template:
    metadata:
      labels:
        app: rewards-server
    spec:
      containers:
        - name: rewards-server
          image: ${CONTAINER_REGISTRY}/rewards-server:${IMAGE_TAG}
          env:
            - name: DATABASE_HOST
              value: "57.151.72.86"
            - name: DATABASE_NAME
              value: dashboard_prod
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: REWARDS_SERVER
            - name: DEFAULT_DEPIN_PROGRAM_ID
              value: D1sMCRu3tRwCviHUDj69WrRQzDoVKd2m2YKydRyauYmJ
            - name: NODE_ENV
              value: production
            - name: REWARDS_MODE
              value: production
            - name: SOLANA_ENV
              value: mainnet
            - name: SOLANA_API_URL
              value: https://mainnet.helius-rpc.com/
            - name: PORT
              value: "80"
            - name: RABBIT_HOST
              value: 64.236.65.232:5672
            - name: WUBI_API_QUEUE
              value: WUBI_API_QUEUE_PROD
            - name: WUBI_API_QUEUE_RESPONSE
              value: REWARDS_SERVER_WUBI_PROD
            - name: WUPI_API_QUEUE
              value: WUPI_API_QUEUE_PROD
            - name: WUPI_API_QUEUE_RESPONSE
              value: REWARDS_SERVER_WUPI_PROD
            - name: NAS_API
              value: https://nas.api.wayru.tech
            - name: RABBIT_RATE_LIMIT_PER_SECOND
              value: "4"
            - name: DISABLED_REWARD_PROGRAM
              value: "false"
            - name: NAS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rewards-server-secrets
                  key: NAS_API_KEY
            - name: SOLANA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rewards-server-secrets
                  key: SOLANA_API_KEY
            - name: SOLANA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: rewards-server-secrets
                  key: SOLANA_PRIVATE_KEY
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rewards-server-secrets
                  key: DATABASE_PASSWORD
            - name: RABBIT_PASS
              valueFrom:
                secretKeyRef:
                  name: rewards-server-secrets
                  key: RABBIT_PASS
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: rewards-server-secrets
                  key: RABBIT_USER

          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
